language: python
python:
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

install:
  - ./bootstrap.sh
  - bin/buildout

script:
  - bin/pytest
